
import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'zh' | 'es' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.about': 'About',
    'nav.services': 'Services',
    'nav.why': 'Why Us',
    'nav.contact': 'Contact Us',
    
    // Hero section
    'hero.title': 'Translating Innovations for the US Market',
    'hero.subtitle': 'Building meaningful partnerships between manufacturers and US consumers.',
    'hero.cta': 'Talk to Us',
    'hero.services': 'Our Services',
    
    // Expertise section
    'expertise.title': 'Our Expertise',
    'expertise.pmf.title': 'Product-Market Fit',
    'expertise.pmf.desc': 'We analyze U.S. consumer expectations and preferences to align your products with market demands.',
    'expertise.localization.title': 'Localization Advisory',
    'expertise.localization.desc': 'Cultural nuances matter. We help adapt your product, messaging, and experience for U.S. consumers.',
    'expertise.channel.title': 'Channel Strategy',
    'expertise.channel.desc': 'Navigate the complex U.S. retail and e-commerce landscape with our expert guidance.',
    'expertise.learn': 'Learn more',
    
    // Strategic partner section
    'partner.title': 'A Strategic Partner',
    'partner.desc': 'asentio combines deep market knowledge with cross-cultural expertise to help your brand navigate the crucial product-market fit challenges in the U.S.',
    'partner.cta': 'Why Choose asentio',
    'partner.expertise.title': 'Cross-Cultural Expertise',
    'partner.expertise.market': 'Deep understanding of both global and U.S. markets',
    'partner.expertise.team': 'Bilingual team with bicultural experience',
    'partner.expertise.insights': 'Strategic insights that bridge East and West',
    
    // CTA section
    'cta.title': 'Ready to Succeed in the U.S. Market?',
    'cta.desc': 'Let\'s discuss how we can help your consumer electronics brand achieve product-market fit in the United States.',
    'cta.contact': 'Contact Us',
    
    // About page
    'about.banner.text': 'We help consumer electronics brands achieve product-market fit in the United States through strategic guidance and cross-cultural expertise.',
    'about.who.title': 'Who We Are',
    'about.who.p1': 'Asentio is a cross-border strategic consultancy that helps international technology companies succeed in the U.S. market.',
    'about.who.p2': 'Founded by professionals with deep experience in both global and American markets, we specialize in translating global innovation into local success.',
    'about.who.p3': 'Our team blends technical expertise with cultural and market insight to ensure your product resonates with U.S. consumer and customers - without losing the essence of your brand.',
    'about.who.p4': 'We also work with U.S. companies looking to collaborate with or source from China, bridging strategic and cultural gaps to create lasting partnerships.',
    'about.team.title': 'Team',
    'about.team.chester': '20+ years experience in strategy and finance, bringing brands and products into new markets, building large teams and scaling businesses.',
    'about.team.jon': '20+ years in consumer electronics, mobile devices, and electric vehicles across China, the US and the EU. Product management + UI/UX expert.',
    'about.cta.title': 'Ready to bridge the gap?',
    'about.cta.desc': 'Let\'s discuss how our expertise can help your brand succeed in the U.S. market.',
    'about.cta.button': 'Get in Touch',
    
    // Services page
    'services.hero.title': 'Our',
    'services.hero.title.highlight': 'Services',
    'services.hero.subtitle': 'Strategic guidance to help global consumer electronics brands succeed in the U.S. market.',
    'services.what.title': 'What We Do',
    'services.what.subtitle': 'Comprehensive solutions designed to bridge the gap between global innovation and US market success',
    'services.product.title': 'Product Strategy & Market Fit',
    'services.product.item1': 'Heuristic UX/UI evaluations for U.S. users',
    'services.product.item2': 'Industrial design and packaging reviews',
    'services.product.item3': 'Cultural fit analysis to adapt branding and messaging',
    'services.product.item4': 'Competitive benchmarking',
    'services.gtm.title': 'Go-To-Market',
    'services.gtm.item1': 'Consumer and enterprise GTM strategy and execution',
    'services.gtm.item2': 'Channel development: retail, distributor, and direct sales',
    'services.gtm.item3': 'Strategic partnership identification and engagement',
    'services.gtm.item4': 'Trade show and event strategy',
    'services.branding.title': 'Branding & Communication',
    'services.branding.item1': 'Positioning and messaging tailored to Western audiences',
    'services.branding.item2': 'Visual identity consulting',
    'services.branding.item3': 'Launch narrative and marketing content support',
    'services.process.title': 'Our Process',
    'services.process.subtitle': 'A proven methodology that transforms market challenges into strategic opportunities',
    'services.process.discovery.title': 'Discovery',
    'services.process.discovery.desc': 'In-depth analysis of your product and business objectives',
    'services.process.assessment.title': 'Assessment',
    'services.process.assessment.desc': 'Market evaluation and competitive positioning analysis',
    'services.process.strategy.title': 'Strategy',
    'services.process.strategy.desc': 'Customized recommendations and action plan development',
    'services.process.implementation.title': 'Implementation',
    'services.process.implementation.desc': 'Ongoing guidance and support during execution',
    'services.cta.title': 'Ready to Transform Your',
    'services.cta.title.highlight': 'U.S. Market Approach?',
    'services.cta.subtitle': 'Contact us today to discuss how our services can help your brand succeed in the American market.',
    'services.cta.button': 'Start the Conversation',
    
    // Contact page
    'contact.hero.title': 'Contact Us',
    'contact.hero.subtitle': 'Let\'s discuss how we can help your brand succeed in the U.S. market.',
    'contact.form.title': 'Get in Touch',
    'contact.form.subtitle': 'Ready to explore how asentio can help your brand achieve product-market fit in the U.S.? We\'re here to answer your questions and discuss your specific needs.',
    'contact.form.email': 'Email',
    'contact.form.website': 'Website',
    'contact.form.how': 'How We Work',
    'contact.form.how.desc': 'After receiving your inquiry, we\'ll schedule an initial consultation to understand your specific goals and challenges. From there, we\'ll propose a tailored approach to help your brand succeed in the U.S. market.',
    'contact.form.send.title': 'Send Us a Message',
    'contact.form.name': 'Name',
    'contact.form.company': 'Company',
    'contact.form.message': 'Message',
    'contact.form.sending': 'Sending...',
    'contact.form.send': 'Send Message',
    'contact.why.title': 'Why Work With Us',
    'contact.why.focus.title': 'Specialized Focus',
    'contact.why.focus.desc': 'We exclusively help global consumer electronics brands succeed in the U.S. market.',
    'contact.why.expertise.title': 'Cross-Cultural Expertise',
    'contact.why.expertise.desc': 'Our bicultural team understands both global and American business environments.',
    'contact.why.approach.title': 'Strategic Approach',
    'contact.why.approach.desc': 'We focus on product-market fit before marketing to ensure sustainable success.',
    'contact.success.title': 'Message sent',
    'contact.success.desc': 'Thank you for contacting asentio. We\'ll be in touch soon.',
    
    // Footer
    'footer.tagline': 'Aligning Global Innovations with US Market Expectations',
    'footer.copyright': 'All rights reserved.',
    'footer.quicklinks': 'Quick Links',
    'footer.contact': 'Contact',
    'footer.whyus': 'Why asentio',
    
    // Experience Framework
    'framework.title': 'Our Approach',
    'framework.subtitle': 'The Consumer Experience Framework is holistic model that maps the <strong>emotional and behavioral journey</strong> a consumer goes through with a product or brand.',
    'framework.hover': 'Hover to explore',
    'framework.focus': 'Focus',
    'framework.channels': 'Channels',
    'framework.touchpoints': 'Touchpoints',
    'framework.hover.details': 'Hover over a stage to see details',
    'framework.aware': 'Aware',
    'framework.aware.objective': 'Make the consumer aware of the product, brand, or solution.',
    'framework.aware.focus': 'Visibility, discovery, relevance',
    'framework.aware.channels': 'Advertising, PR, SEO, word of mouth, influencer mentions',
    'framework.aware.touchpoints': 'Social posts, landing pages, trade shows, media coverage',
    'framework.arouse': 'Arouse',
    'framework.arouse.objective': 'Spark interest and desire to learn more or act.',
    'framework.arouse.focus': 'Emotional connection, differentiation, aspiration',
    'framework.arouse.channels': 'Brand storytelling, product demos, experiential content',
    'framework.arouse.touchpoints': 'Videos, product packaging, in-store experiences, testimonials',
    'framework.acquire': 'Acquire',
    'framework.acquire.objective': 'Drive the user to purchase or sign up.',
    'framework.acquire.focus': 'Ease, trust, incentive',
    'framework.acquire.channels': 'E-commerce platforms, sales teams, retail stores',
    'framework.acquire.touchpoints': 'Checkout flow, pricing page, promotions, trial offers',
    'framework.use': 'Use',
    'framework.use.objective': 'Ensure a satisfying and delightful product usage experience.',
    'framework.use.focus': 'Usability, onboarding, feature clarity',
    'framework.use.channels': 'Product UX, user guides, customer support',
    'framework.use.touchpoints': 'App interface, quick-start guides, customer success',
    'framework.reflect': 'Reflect',
    'framework.reflect.objective': 'Drive loyalty, advocacy, or repeat engagement.',
    'framework.reflect.focus': 'Value recognition, memory, identity',
    'framework.reflect.channels': 'Post-purchase emails, loyalty programs, community',
    'framework.reflect.touchpoints': 'Follow-up surveys, user forums, case studies'
  },
  zh: {
    // Navigation
    'nav.home': '首页',
    'nav.about': '关于我们',
    'nav.services': '服务',
    'nav.why': '为什么选择我们',
    'nav.contact': '联系我们',
    
    // Hero section
    'hero.title': '为美国市场转化创新',
    'hero.subtitle': '在制造商和美国消费者之间建立有意义的合作伙伴关系。',
    'hero.cta': '联系我们',
    'hero.services': '我们的服务',
    
    // Expertise section
    'expertise.title': '我们的专业能力',
    'expertise.pmf.title': '产品市场契合度',
    'expertise.pmf.desc': '我们分析美国消费者的期望和偏好，使您的产品与市场需求保持一致。',
    'expertise.localization.title': '本土化咨询',
    'expertise.localization.desc': '文化细节很重要。我们帮助您调整产品、信息传递和用户体验以适应美国消费者。',
    'expertise.channel.title': '渠道策略',
    'expertise.channel.desc': '在我们专家指导下，导航复杂的美国零售和电子商务环境。',
    'expertise.learn': '了解更多',
    
    // Strategic partner section
    'partner.title': '战略合作伙伴',
    'partner.desc': 'asentio结合深厚的市场知识和跨文化专业能力，帮助您的品牌应对在美国市场的关键产品市场契合度挑战。',
    'partner.cta': '为什么选择asentio',
    'partner.expertise.title': '跨文化专业能力',
    'partner.expertise.market': '深度了解中美两国市场',
    'partner.expertise.team': '具有双文化经验的双语团队',
    'partner.expertise.insights': '连接东西方的战略洞察',
    
    // CTA section
    'cta.title': '准备好在美国市场取得成功了吗？',
    'cta.desc': '让我们讨论如何帮助您的消费电子品牌在美国实现产品市场契合度。',
    'cta.contact': '联系我们',
    
    // About page
    'about.banner.text': '我们通过战略指导和跨文化专业知识，帮助消费电子品牌在美国实现产品市场契合度。',
    'about.who.title': '我们是谁',
    'about.who.p1': 'Asentio是一家跨境战略咨询公司，帮助国际科技公司在美国市场取得成功。',
    'about.who.p2': '由在中美两国市场拥有丰富经验的专业人士创立，我们专门将全球创新转化为本地成功。',
    'about.who.p3': '我们的团队将技术专长与文化和市场洞察相结合，确保您的产品与美国消费者和客户产生共鸣——同时不失去您品牌的本质。',
    'about.who.p4': '我们还与寻求与中国合作或从中国采购的美国公司合作，弥合战略和文化差距，创造持久的合作伙伴关系。',
    'about.team.title': '团队',
    'about.team.chester': '20多年战略和金融经验，将品牌和产品带入新市场，建立大型团队并扩展业务。',
    'about.team.jon': '20多年消费电子、移动设备和电动汽车领域经验，跨越中国、美国和欧盟。产品管理+UI/UX专家。',
    'about.cta.title': '准备好搭建桥梁了吗？',
    'about.cta.desc': '让我们讨论我们的专业知识如何帮助您的品牌在美国市场取得成功。',
    'about.cta.button': '联系我们',
    
    // Services page
    'services.hero.title': '我们的',
    'services.hero.title.highlight': '服务',
    'services.hero.subtitle': '为全球消费电子品牌在美国市场取得成功提供战略指导。',
    'services.what.title': '我们的服务内容',
    'services.what.subtitle': '旨在弥合全球创新与美国市场成功之间差距的综合解决方案',
    'services.product.title': '产品策略与市场契合度',
    'services.product.item1': '针对美国用户的启发式用户体验/界面评估',
    'services.product.item2': '工业设计和包装审查',
    'services.product.item3': '文化契合度分析，调整品牌和信息传递',
    'services.product.item4': '竞争对手基准分析',
    'services.gtm.title': '市场推广',
    'services.gtm.item1': '消费者和企业市场推广策略与执行',
    'services.gtm.item2': '渠道开发：零售、分销商和直销',
    'services.gtm.item3': '战略合作伙伴识别与参与',
    'services.gtm.item4': '贸易展览和活动策略',
    'services.branding.title': '品牌与传播',
    'services.branding.item1': '针对西方受众的定位和信息传递',
    'services.branding.item2': '视觉识别咨询',
    'services.branding.item3': '发布叙述和营销内容支持',
    'services.process.title': '我们的流程',
    'services.process.subtitle': '将市场挑战转化为战略机遇的成熟方法论',
    'services.process.discovery.title': '发现',
    'services.process.discovery.desc': '深入分析您的产品和业务目标',
    'services.process.assessment.title': '评估',
    'services.process.assessment.desc': '市场评估和竞争定位分析',
    'services.process.strategy.title': '策略',
    'services.process.strategy.desc': '定制建议和行动计划制定',
    'services.process.implementation.title': '实施',
    'services.process.implementation.desc': '执行过程中的持续指导和支持',
    'services.cta.title': '准备好转变您的',
    'services.cta.title.highlight': '美国市场方法了吗？',
    'services.cta.subtitle': '今天就联系我们，讨论我们的服务如何帮助您的品牌在美国市场取得成功。',
    'services.cta.button': '开始对话',
    
    // Contact page
    'contact.hero.title': '联系我们',
    'contact.hero.subtitle': '让我们讨论如何帮助您的品牌在美国市场取得成功。',
    'contact.form.title': '联系我们',
    'contact.form.subtitle': '准备好探索asentio如何帮助您的品牌在美国实现产品市场契合度？我们在这里回答您的问题并讨论您的具体需求。',
    'contact.form.email': '邮箱',
    'contact.form.website': '网站',
    'contact.form.how': '我们的工作方式',
    'contact.form.how.desc': '收到您的询问后，我们将安排初步咨询，了解您的具体目标和挑战。然后，我们将提出量身定制的方法，帮助您的品牌在美国市场取得成功。',
    'contact.form.send.title': '给我们发送消息',
    'contact.form.name': '姓名',
    'contact.form.company': '公司',
    'contact.form.message': '消息',
    'contact.form.sending': '发送中...',
    'contact.form.send': '发送消息',
    'contact.why.title': '为什么与我们合作',
    'contact.why.focus.title': '专业专注',
    'contact.why.focus.desc': '我们专门帮助全球消费电子品牌在美国市场取得成功。',
    'contact.why.expertise.title': '跨文化专业知识',
    'contact.why.expertise.desc': '我们的双文化团队了解中美两国的商业环境。',
    'contact.why.approach.title': '战略方法',
    'contact.why.approach.desc': '我们在营销之前专注于产品市场契合度，以确保可持续的成功。',
    'contact.success.title': '消息已发送',
    'contact.success.desc': '感谢您联系asentio。我们很快会与您联系。',
    
    // Footer
    'footer.tagline': '使全球创新与美国市场期望保持一致',
    'footer.copyright': '版权所有。',
    'footer.quicklinks': '快速链接',
    'footer.contact': '联系方式',
    'footer.whyus': '为什么选择asentio',
    
    // Experience Framework
    'framework.title': '我们的方法',
    'framework.subtitle': '消费者体验框架是一个整体模型，映射消费者与产品或品牌之间的<strong>情感和行为旅程</strong>。',
    'framework.hover': '悬停以探索',
    'framework.focus': '重点',
    'framework.channels': '渠道',
    'framework.touchpoints': '接触点',
    'framework.hover.details': '悬停在某个阶段查看详情',
    'framework.aware': '认知',
    'framework.aware.objective': '让消费者了解产品、品牌或解决方案。',
    'framework.aware.focus': '可见性、发现、相关性',
    'framework.aware.channels': '广告、公关、SEO、口碑、网红提及',
    'framework.aware.touchpoints': '社交帖子、着陆页、展会、媒体报道',
    'framework.arouse': '激发',
    'framework.arouse.objective': '激发兴趣和进一步了解或行动的欲望。',
    'framework.arouse.focus': '情感连接、差异化、愿望',
    'framework.arouse.channels': '品牌故事、产品演示、体验内容',
    'framework.arouse.touchpoints': '视频、产品包装、店内体验、客户评价',
    'framework.acquire': '获取',
    'framework.acquire.objective': '推动用户购买或注册。',
    'framework.acquire.focus': '便捷、信任、激励',
    'framework.acquire.channels': '电商平台、销售团队、零售店',
    'framework.acquire.touchpoints': '结账流程、定价页面、促销、试用优惠',
    'framework.use': '使用',
    'framework.use.objective': '确保满意和愉悦的产品使用体验。',
    'framework.use.focus': '可用性、引导、功能清晰度',
    'framework.use.channels': '产品用户体验、用户指南、客户支持',
    'framework.use.touchpoints': '应用界面、快速入门指南、客户成功',
    'framework.reflect': '反思',
    'framework.reflect.objective': '推动忠诚度、倡导或重复参与。',
    'framework.reflect.focus': '价值认可、记忆、身份',
    'framework.reflect.channels': '购后邮件、忠诚度计划、社区',
    'framework.reflect.touchpoints': '跟进调查、用户论坛、案例研究'
  },
  es: {
    // Navigation
    'nav.home': 'Inicio',
    'nav.about': 'Nosotros',
    'nav.services': 'Servicios',
    'nav.why': 'Por qué elegirnos',
    'nav.contact': 'Contáctenos',
    
    // Hero section
    'hero.title': 'Traduciendo Innovaciones para el Mercado Estadounidense',
    'hero.subtitle': 'Construyendo alianzas significativas entre fabricantes y consumidores estadounidenses.',
    'hero.cta': 'Hablemos',
    'hero.services': 'Nuestros Servicios',
    
    // Expertise section
    'expertise.title': 'Nuestra Experiencia',
    'expertise.pmf.title': 'Ajuste Producto-Mercado',
    'expertise.pmf.desc': 'Analizamos las expectativas y preferencias de los consumidores estadounidenses para alinear sus productos con las demandas del mercado.',
    'expertise.localization.title': 'Asesoría de Localización',
    'expertise.localization.desc': 'Los matices culturales importan. Ayudamos a adaptar su producto, mensajes y experiencia para consumidores estadounidenses.',
    'expertise.channel.title': 'Estrategia de Canales',
    'expertise.channel.desc': 'Navegue el complejo panorama minorista y de comercio electrónico de EE.UU. con nuestra guía experta.',
    'expertise.learn': 'Más información',
    
    // Strategic partner section
    'partner.title': 'Un Socio Estratégico',
    'partner.desc': 'asentio combina profundo conocimiento del mercado con experiencia intercultural para ayudar a su marca a navegar los desafíos cruciales de ajuste producto-mercado en EE.UU.',
    'partner.cta': 'Por qué elegir asentio',
    'partner.expertise.title': 'Experiencia Intercultural',
    'partner.expertise.market': 'Profundo entendimiento de mercados globales y estadounidenses',
    'partner.expertise.team': 'Equipo bilingüe con experiencia bicultural',
    'partner.expertise.insights': 'Perspectivas estratégicas que conectan Oriente y Occidente',
    
    // CTA section
    'cta.title': '¿Listo para Triunfar en el Mercado Estadounidense?',
    'cta.desc': 'Hablemos sobre cómo podemos ayudar a su marca de electrónica de consumo a lograr el ajuste producto-mercado en Estados Unidos.',
    'cta.contact': 'Contáctenos',
    
    // About page
    'about.banner.text': 'Ayudamos a marcas de electrónica de consumo a lograr el ajuste producto-mercado en Estados Unidos a través de orientación estratégica y experiencia intercultural.',
    'about.who.title': 'Quiénes Somos',
    'about.who.p1': 'Asentio es una consultora estratégica transfronteriza que ayuda a empresas tecnológicas internacionales a triunfar en el mercado estadounidense.',
    'about.who.p2': 'Fundada por profesionales con amplia experiencia en mercados globales y estadounidenses, nos especializamos en traducir innovación global en éxito local.',
    'about.who.p3': 'Nuestro equipo combina experiencia técnica con conocimiento cultural y de mercado para asegurar que su producto resuene con consumidores y clientes estadounidenses, sin perder la esencia de su marca.',
    'about.who.p4': 'También trabajamos con empresas estadounidenses que buscan colaborar o abastecerse de China, cerrando brechas estratégicas y culturales para crear alianzas duraderas.',
    'about.team.title': 'Equipo',
    'about.team.chester': 'Más de 20 años de experiencia en estrategia y finanzas, llevando marcas y productos a nuevos mercados, construyendo grandes equipos y escalando negocios.',
    'about.team.jon': 'Más de 20 años en electrónica de consumo, dispositivos móviles y vehículos eléctricos en China, EE.UU. y la UE. Experto en gestión de productos y UI/UX.',
    'about.cta.title': '¿Listo para cerrar la brecha?',
    'about.cta.desc': 'Hablemos sobre cómo nuestra experiencia puede ayudar a su marca a triunfar en el mercado estadounidense.',
    'about.cta.button': 'Contáctenos',
    
    // Services page
    'services.hero.title': 'Nuestros',
    'services.hero.title.highlight': 'Servicios',
    'services.hero.subtitle': 'Orientación estratégica para ayudar a marcas globales de electrónica de consumo a triunfar en el mercado estadounidense.',
    'services.what.title': 'Lo Que Hacemos',
    'services.what.subtitle': 'Soluciones integrales diseñadas para cerrar la brecha entre la innovación global y el éxito en el mercado estadounidense',
    'services.product.title': 'Estrategia de Producto y Ajuste de Mercado',
    'services.product.item1': 'Evaluaciones heurísticas de UX/UI para usuarios estadounidenses',
    'services.product.item2': 'Revisiones de diseño industrial y empaque',
    'services.product.item3': 'Análisis de ajuste cultural para adaptar marca y mensajes',
    'services.product.item4': 'Benchmarking competitivo',
    'services.gtm.title': 'Estrategia de Lanzamiento',
    'services.gtm.item1': 'Estrategia y ejecución GTM para consumidores y empresas',
    'services.gtm.item2': 'Desarrollo de canales: retail, distribuidores y ventas directas',
    'services.gtm.item3': 'Identificación y gestión de alianzas estratégicas',
    'services.gtm.item4': 'Estrategia de ferias y eventos',
    'services.branding.title': 'Marca y Comunicación',
    'services.branding.item1': 'Posicionamiento y mensajes adaptados a audiencias occidentales',
    'services.branding.item2': 'Consultoría de identidad visual',
    'services.branding.item3': 'Soporte de narrativa de lanzamiento y contenido de marketing',
    'services.process.title': 'Nuestro Proceso',
    'services.process.subtitle': 'Una metodología probada que transforma desafíos de mercado en oportunidades estratégicas',
    'services.process.discovery.title': 'Descubrimiento',
    'services.process.discovery.desc': 'Análisis profundo de su producto y objetivos de negocio',
    'services.process.assessment.title': 'Evaluación',
    'services.process.assessment.desc': 'Evaluación de mercado y análisis de posicionamiento competitivo',
    'services.process.strategy.title': 'Estrategia',
    'services.process.strategy.desc': 'Recomendaciones personalizadas y desarrollo de plan de acción',
    'services.process.implementation.title': 'Implementación',
    'services.process.implementation.desc': 'Orientación y soporte continuo durante la ejecución',
    'services.cta.title': '¿Listo para Transformar su',
    'services.cta.title.highlight': 'Enfoque en el Mercado de EE.UU.?',
    'services.cta.subtitle': 'Contáctenos hoy para hablar sobre cómo nuestros servicios pueden ayudar a su marca a triunfar en el mercado estadounidense.',
    'services.cta.button': 'Iniciar Conversación',
    
    // Contact page
    'contact.hero.title': 'Contáctenos',
    'contact.hero.subtitle': 'Hablemos sobre cómo podemos ayudar a su marca a triunfar en el mercado estadounidense.',
    'contact.form.title': 'Póngase en Contacto',
    'contact.form.subtitle': '¿Listo para explorar cómo asentio puede ayudar a su marca a lograr el ajuste producto-mercado en EE.UU.? Estamos aquí para responder sus preguntas y discutir sus necesidades específicas.',
    'contact.form.email': 'Correo Electrónico',
    'contact.form.website': 'Sitio Web',
    'contact.form.how': 'Cómo Trabajamos',
    'contact.form.how.desc': 'Después de recibir su consulta, programaremos una consulta inicial para entender sus objetivos y desafíos específicos. A partir de ahí, propondremos un enfoque personalizado para ayudar a su marca a triunfar en el mercado estadounidense.',
    'contact.form.send.title': 'Envíenos un Mensaje',
    'contact.form.name': 'Nombre',
    'contact.form.company': 'Empresa',
    'contact.form.message': 'Mensaje',
    'contact.form.sending': 'Enviando...',
    'contact.form.send': 'Enviar Mensaje',
    'contact.why.title': 'Por Qué Trabajar Con Nosotros',
    'contact.why.focus.title': 'Enfoque Especializado',
    'contact.why.focus.desc': 'Ayudamos exclusivamente a marcas globales de electrónica de consumo a triunfar en el mercado estadounidense.',
    'contact.why.expertise.title': 'Experiencia Intercultural',
    'contact.why.expertise.desc': 'Nuestro equipo bicultural entiende los entornos empresariales globales y estadounidenses.',
    'contact.why.approach.title': 'Enfoque Estratégico',
    'contact.why.approach.desc': 'Nos enfocamos en el ajuste producto-mercado antes del marketing para asegurar éxito sostenible.',
    'contact.success.title': 'Mensaje enviado',
    'contact.success.desc': 'Gracias por contactar a asentio. Nos pondremos en contacto pronto.',
    
    // Footer
    'footer.tagline': 'Alineando Innovaciones Globales con las Expectativas del Mercado Estadounidense',
    'footer.copyright': 'Todos los derechos reservados.',
    'footer.quicklinks': 'Enlaces Rápidos',
    'footer.contact': 'Contacto',
    'footer.whyus': 'Por qué asentio',
    
    // Experience Framework
    'framework.title': 'Nuestro Enfoque',
    'framework.subtitle': 'El Marco de Experiencia del Consumidor es un modelo holístico que mapea el <strong>viaje emocional y conductual</strong> que un consumidor atraviesa con un producto o marca.',
    'framework.hover': 'Pasa el cursor para explorar',
    'framework.focus': 'Enfoque',
    'framework.channels': 'Canales',
    'framework.touchpoints': 'Puntos de Contacto',
    'framework.hover.details': 'Pasa el cursor sobre una etapa para ver detalles',
    'framework.aware': 'Conocer',
    'framework.aware.objective': 'Hacer que el consumidor conozca el producto, marca o solución.',
    'framework.aware.focus': 'Visibilidad, descubrimiento, relevancia',
    'framework.aware.channels': 'Publicidad, relaciones públicas, SEO, boca a boca, menciones de influencers',
    'framework.aware.touchpoints': 'Publicaciones sociales, páginas de destino, ferias comerciales, cobertura mediática',
    'framework.arouse': 'Despertar',
    'framework.arouse.objective': 'Despertar interés y deseo de aprender más o actuar.',
    'framework.arouse.focus': 'Conexión emocional, diferenciación, aspiración',
    'framework.arouse.channels': 'Narrativa de marca, demos de producto, contenido experiencial',
    'framework.arouse.touchpoints': 'Videos, empaque de producto, experiencias en tienda, testimonios',
    'framework.acquire': 'Adquirir',
    'framework.acquire.objective': 'Impulsar al usuario a comprar o registrarse.',
    'framework.acquire.focus': 'Facilidad, confianza, incentivo',
    'framework.acquire.channels': 'Plataformas de comercio electrónico, equipos de ventas, tiendas minoristas',
    'framework.acquire.touchpoints': 'Flujo de pago, página de precios, promociones, ofertas de prueba',
    'framework.use': 'Usar',
    'framework.use.objective': 'Asegurar una experiencia de uso satisfactoria y encantadora.',
    'framework.use.focus': 'Usabilidad, incorporación, claridad de funciones',
    'framework.use.channels': 'UX del producto, guías de usuario, soporte al cliente',
    'framework.use.touchpoints': 'Interfaz de app, guías de inicio rápido, éxito del cliente',
    'framework.reflect': 'Reflexionar',
    'framework.reflect.objective': 'Impulsar lealtad, promoción o compromiso repetido.',
    'framework.reflect.focus': 'Reconocimiento de valor, memoria, identidad',
    'framework.reflect.channels': 'Correos post-compra, programas de lealtad, comunidad',
    'framework.reflect.touchpoints': 'Encuestas de seguimiento, foros de usuarios, casos de estudio'
  },
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.about': 'Über uns',
    'nav.services': 'Dienstleistungen',
    'nav.why': 'Warum wir',
    'nav.contact': 'Kontakt',
    
    // Hero section
    'hero.title': 'Innovationen für den US-Markt übersetzen',
    'hero.subtitle': 'Aufbau bedeutungsvoller Partnerschaften zwischen Herstellern und US-Verbrauchern.',
    'hero.cta': 'Sprechen Sie mit uns',
    'hero.services': 'Unsere Dienstleistungen',
    
    // Expertise section
    'expertise.title': 'Unsere Expertise',
    'expertise.pmf.title': 'Produkt-Markt-Fit',
    'expertise.pmf.desc': 'Wir analysieren die Erwartungen und Präferenzen der US-Verbraucher, um Ihre Produkte an die Marktanforderungen anzupassen.',
    'expertise.localization.title': 'Lokalisierungsberatung',
    'expertise.localization.desc': 'Kulturelle Nuancen sind wichtig. Wir helfen dabei, Ihr Produkt, Ihre Botschaften und Ihr Erlebnis für US-Verbraucher anzupassen.',
    'expertise.channel.title': 'Kanalstrategie',
    'expertise.channel.desc': 'Navigieren Sie mit unserer Expertenberatung durch die komplexe US-Einzelhandels- und E-Commerce-Landschaft.',
    'expertise.learn': 'Mehr erfahren',
    
    // Strategic partner section
    'partner.title': 'Ein strategischer Partner',
    'partner.desc': 'asentio kombiniert tiefes Marktwissen mit interkultureller Expertise, um Ihrer Marke bei den entscheidenden Produkt-Markt-Fit-Herausforderungen in den USA zu helfen.',
    'partner.cta': 'Warum asentio wählen',
    'partner.expertise.title': 'Interkulturelle Expertise',
    'partner.expertise.market': 'Tiefes Verständnis sowohl globaler als auch US-amerikanischer Märkte',
    'partner.expertise.team': 'Zweisprachiges Team mit bikultureller Erfahrung',
    'partner.expertise.insights': 'Strategische Einblicke, die Ost und West verbinden',
    
    // CTA section
    'cta.title': 'Bereit für den Erfolg auf dem US-Markt?',
    'cta.desc': 'Lassen Sie uns besprechen, wie wir Ihrer Unterhaltungselektronik-Marke helfen können, den Produkt-Markt-Fit in den USA zu erreichen.',
    'cta.contact': 'Kontaktieren Sie uns',
    
    // About page
    'about.banner.text': 'Wir helfen Unterhaltungselektronik-Marken, den Produkt-Markt-Fit in den USA durch strategische Beratung und interkulturelle Expertise zu erreichen.',
    'about.who.title': 'Wer wir sind',
    'about.who.p1': 'Asentio ist eine grenzüberschreitende strategische Beratung, die internationalen Technologieunternehmen zum Erfolg auf dem US-Markt verhilft.',
    'about.who.p2': 'Gegründet von Fachleuten mit umfassender Erfahrung sowohl auf globalen als auch auf amerikanischen Märkten, sind wir darauf spezialisiert, globale Innovation in lokalen Erfolg zu übersetzen.',
    'about.who.p3': 'Unser Team verbindet technische Expertise mit kulturellem und Marktverständnis, um sicherzustellen, dass Ihr Produkt bei US-Verbrauchern und Kunden Anklang findet – ohne die Essenz Ihrer Marke zu verlieren.',
    'about.who.p4': 'Wir arbeiten auch mit US-Unternehmen zusammen, die mit China kooperieren oder von dort beziehen möchten, und überbrücken strategische und kulturelle Lücken für dauerhafte Partnerschaften.',
    'about.team.title': 'Team',
    'about.team.chester': 'Über 20 Jahre Erfahrung in Strategie und Finanzen, bringt Marken und Produkte in neue Märkte, baut große Teams auf und skaliert Unternehmen.',
    'about.team.jon': 'Über 20 Jahre in Unterhaltungselektronik, Mobilgeräten und Elektrofahrzeugen in China, den USA und der EU. Produktmanagement + UI/UX-Experte.',
    'about.cta.title': 'Bereit, die Lücke zu schließen?',
    'about.cta.desc': 'Lassen Sie uns besprechen, wie unsere Expertise Ihrer Marke zum Erfolg auf dem US-Markt verhelfen kann.',
    'about.cta.button': 'Kontakt aufnehmen',
    
    // Services page
    'services.hero.title': 'Unsere',
    'services.hero.title.highlight': 'Dienstleistungen',
    'services.hero.subtitle': 'Strategische Beratung, um globalen Unterhaltungselektronik-Marken zum Erfolg auf dem US-Markt zu verhelfen.',
    'services.what.title': 'Was wir tun',
    'services.what.subtitle': 'Umfassende Lösungen, um die Lücke zwischen globaler Innovation und US-Markterfolg zu schließen',
    'services.product.title': 'Produktstrategie & Markt-Fit',
    'services.product.item1': 'Heuristische UX/UI-Bewertungen für US-Nutzer',
    'services.product.item2': 'Industriedesign- und Verpackungsprüfungen',
    'services.product.item3': 'Kulturelle Fit-Analyse zur Anpassung von Marke und Botschaften',
    'services.product.item4': 'Wettbewerbs-Benchmarking',
    'services.gtm.title': 'Go-To-Market',
    'services.gtm.item1': 'Verbraucher- und Unternehmens-GTM-Strategie und -Umsetzung',
    'services.gtm.item2': 'Kanalentwicklung: Einzelhandel, Vertrieb und Direktverkauf',
    'services.gtm.item3': 'Identifizierung und Engagement strategischer Partner',
    'services.gtm.item4': 'Messe- und Veranstaltungsstrategie',
    'services.branding.title': 'Marke & Kommunikation',
    'services.branding.item1': 'Positionierung und Botschaften für westliche Zielgruppen',
    'services.branding.item2': 'Beratung zur visuellen Identität',
    'services.branding.item3': 'Launch-Narrativ und Marketing-Content-Unterstützung',
    'services.process.title': 'Unser Prozess',
    'services.process.subtitle': 'Eine bewährte Methodik, die Marktherausforderungen in strategische Chancen verwandelt',
    'services.process.discovery.title': 'Entdeckung',
    'services.process.discovery.desc': 'Tiefgehende Analyse Ihres Produkts und Ihrer Geschäftsziele',
    'services.process.assessment.title': 'Bewertung',
    'services.process.assessment.desc': 'Marktbewertung und Wettbewerbspositionsanalyse',
    'services.process.strategy.title': 'Strategie',
    'services.process.strategy.desc': 'Maßgeschneiderte Empfehlungen und Aktionsplanentwicklung',
    'services.process.implementation.title': 'Umsetzung',
    'services.process.implementation.desc': 'Laufende Beratung und Unterstützung bei der Durchführung',
    'services.cta.title': 'Bereit, Ihren',
    'services.cta.title.highlight': 'US-Markt-Ansatz zu transformieren?',
    'services.cta.subtitle': 'Kontaktieren Sie uns heute, um zu besprechen, wie unsere Dienstleistungen Ihrer Marke zum Erfolg auf dem amerikanischen Markt verhelfen können.',
    'services.cta.button': 'Gespräch starten',
    
    // Contact page
    'contact.hero.title': 'Kontaktieren Sie uns',
    'contact.hero.subtitle': 'Lassen Sie uns besprechen, wie wir Ihrer Marke zum Erfolg auf dem US-Markt verhelfen können.',
    'contact.form.title': 'Kontakt aufnehmen',
    'contact.form.subtitle': 'Bereit zu erkunden, wie asentio Ihrer Marke helfen kann, den Produkt-Markt-Fit in den USA zu erreichen? Wir sind hier, um Ihre Fragen zu beantworten und Ihre spezifischen Bedürfnisse zu besprechen.',
    'contact.form.email': 'E-Mail',
    'contact.form.website': 'Webseite',
    'contact.form.how': 'Wie wir arbeiten',
    'contact.form.how.desc': 'Nach Erhalt Ihrer Anfrage vereinbaren wir ein erstes Beratungsgespräch, um Ihre spezifischen Ziele und Herausforderungen zu verstehen. Daraufhin schlagen wir einen maßgeschneiderten Ansatz vor, um Ihrer Marke zum Erfolg auf dem US-Markt zu verhelfen.',
    'contact.form.send.title': 'Senden Sie uns eine Nachricht',
    'contact.form.name': 'Name',
    'contact.form.company': 'Unternehmen',
    'contact.form.message': 'Nachricht',
    'contact.form.sending': 'Wird gesendet...',
    'contact.form.send': 'Nachricht senden',
    'contact.why.title': 'Warum mit uns arbeiten',
    'contact.why.focus.title': 'Spezialisierter Fokus',
    'contact.why.focus.desc': 'Wir helfen ausschließlich globalen Unterhaltungselektronik-Marken zum Erfolg auf dem US-Markt.',
    'contact.why.expertise.title': 'Interkulturelle Expertise',
    'contact.why.expertise.desc': 'Unser bikulturelles Team versteht sowohl globale als auch amerikanische Geschäftsumgebungen.',
    'contact.why.approach.title': 'Strategischer Ansatz',
    'contact.why.approach.desc': 'Wir konzentrieren uns auf Produkt-Markt-Fit vor dem Marketing, um nachhaltigen Erfolg zu gewährleisten.',
    'contact.success.title': 'Nachricht gesendet',
    'contact.success.desc': 'Vielen Dank für Ihre Kontaktaufnahme mit asentio. Wir melden uns bald bei Ihnen.',
    
    // Footer
    'footer.tagline': 'Globale Innovationen mit US-Markterwartungen in Einklang bringen',
    'footer.copyright': 'Alle Rechte vorbehalten.',
    'footer.quicklinks': 'Schnelllinks',
    'footer.contact': 'Kontakt',
    'footer.whyus': 'Warum asentio',
    
    // Experience Framework
    'framework.title': 'Unser Ansatz',
    'framework.subtitle': 'Das Consumer Experience Framework ist ein ganzheitliches Modell, das die <strong>emotionale und verhaltensbezogene Reise</strong> abbildet, die ein Verbraucher mit einem Produkt oder einer Marke durchläuft.',
    'framework.hover': 'Hover zum Erkunden',
    'framework.focus': 'Fokus',
    'framework.channels': 'Kanäle',
    'framework.touchpoints': 'Berührungspunkte',
    'framework.hover.details': 'Fahren Sie über eine Stufe für Details',
    'framework.aware': 'Wahrnehmen',
    'framework.aware.objective': 'Den Verbraucher auf das Produkt, die Marke oder die Lösung aufmerksam machen.',
    'framework.aware.focus': 'Sichtbarkeit, Entdeckung, Relevanz',
    'framework.aware.channels': 'Werbung, PR, SEO, Mundpropaganda, Influencer-Erwähnungen',
    'framework.aware.touchpoints': 'Social Posts, Landing Pages, Messen, Medienberichterstattung',
    'framework.arouse': 'Wecken',
    'framework.arouse.objective': 'Interesse und den Wunsch wecken, mehr zu erfahren oder zu handeln.',
    'framework.arouse.focus': 'Emotionale Verbindung, Differenzierung, Aspiration',
    'framework.arouse.channels': 'Marken-Storytelling, Produktdemos, erlebnisorientierte Inhalte',
    'framework.arouse.touchpoints': 'Videos, Produktverpackung, In-Store-Erlebnisse, Testimonials',
    'framework.acquire': 'Erwerben',
    'framework.acquire.objective': 'Den Nutzer zum Kauf oder zur Anmeldung bewegen.',
    'framework.acquire.focus': 'Einfachheit, Vertrauen, Anreiz',
    'framework.acquire.channels': 'E-Commerce-Plattformen, Vertriebsteams, Einzelhandelsgeschäfte',
    'framework.acquire.touchpoints': 'Checkout-Flow, Preisseite, Aktionen, Testangebote',
    'framework.use': 'Nutzen',
    'framework.use.objective': 'Eine zufriedenstellende und erfreuliche Produktnutzungserfahrung gewährleisten.',
    'framework.use.focus': 'Benutzerfreundlichkeit, Onboarding, Funktionsklarheit',
    'framework.use.channels': 'Produkt-UX, Benutzerhandbücher, Kundensupport',
    'framework.use.touchpoints': 'App-Oberfläche, Schnellstartanleitungen, Kundenerfolg',
    'framework.reflect': 'Reflektieren',
    'framework.reflect.objective': 'Loyalität, Empfehlung oder wiederholtes Engagement fördern.',
    'framework.reflect.focus': 'Werterkennung, Erinnerung, Identität',
    'framework.reflect.channels': 'Nachkauf-E-Mails, Treueprogramme, Community',
    'framework.reflect.touchpoints': 'Follow-up-Umfragen, Benutzerforen, Fallstudien'
  }
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    const langTranslations = translations[language];
    const translatedValue = langTranslations[key as keyof typeof translations['en']];
    // Fall back to English if translation is missing (for es/de placeholders)
    if (!translatedValue) {
      return translations.en[key as keyof typeof translations['en']] || key;
    }
    return translatedValue;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
