import { Contractor, SavedSegment } from './types';

const today = new Date();
const daysAgo = (n: number) => new Date(today.getTime() - n * 86400000).toISOString();

export const seedContractors: Contractor[] = [
  {
    contractor_id: 'c-001',
    company_name: 'Bay Area Premier Flooring',
    dba_name: 'BAPF',
    contractor_type: 'Flooring Installer',
    specialties: ['Hardwood', 'LVP', 'Tile'],
    license_number: 'CSLB-872341',
    license_classification: 'C-15',
    license_status: 'Active',
    license_issue_date: '2014-03-12',
    license_expiration_date: '2026-03-12',
    bond_status: 'Active',
    insurance_status: 'Active',
    address: '1820 W San Carlos St',
    city: 'San Jose',
    county: 'Santa Clara',
    state: 'CA',
    zip_code: '95128',
    latitude: 37.3261,
    longitude: -121.9326,
    phone: '(408) 555-0142',
    website: 'https://baypremierflooring.com',
    email: 'hello@baypremierflooring.com',
    email_verified: true,
    contact_form_url: 'https://baypremierflooring.com/contact',
    review_rating: 4.8,
    review_count: 187,
    source_count: 5,
    source_urls: ['Official License Source', 'Google Business', 'Yelp', 'Company Website', 'Verified Email'],
    years_in_business: 11,
    estimated_company_size: 'Growing Local',
    estimated_business_maturity: 'Premium / Design-Forward',
    service_area: ['San Jose', 'Santa Clara', 'Sunnyvale', 'Mountain View'],
    tags: ['premium', 'residential', 'design-forward'],
    confidence_score: 96,
    last_verified_date: daysAgo(3),
    commercial_residential: 'Residential',
  },
  {
    contractor_id: 'c-002',
    company_name: 'Sunrise General Builders',
    contractor_type: 'General Contractor',
    specialties: ['ADUs', 'Home Additions', 'Remodels'],
    license_number: 'CSLB-661230',
    license_classification: 'B',
    license_status: 'Active',
    license_issue_date: '2008-06-20',
    license_expiration_date: '2025-06-20',
    bond_status: 'Active',
    insurance_status: 'Active',
    address: '2210 21st St',
    city: 'Sacramento',
    county: 'Sacramento',
    state: 'CA',
    zip_code: '95818',
    latitude: 38.5594,
    longitude: -121.4782,
    phone: '(916) 555-0188',
    website: 'https://sunrisegeneralbuilders.com',
    email: 'info@sunrisegb.com',
    email_verified: true,
    review_rating: 4.6,
    review_count: 64,
    source_count: 4,
    source_urls: ['Official License Source', 'Google Business', 'Company Website', 'Verified Email'],
    years_in_business: 17,
    estimated_company_size: 'Mid-Sized',
    estimated_business_maturity: 'Established',
    service_area: ['Sacramento', 'Elk Grove', 'Roseville'],
    tags: ['adu', 'remodel', 'established'],
    confidence_score: 92,
    last_verified_date: daysAgo(7),
    commercial_residential: 'Both',
  },
  {
    contractor_id: 'c-003',
    company_name: 'Coastline Kitchen & Bath',
    contractor_type: 'Kitchen / Bath Remodeler',
    specialties: ['Kitchen Remodel', 'Bath Remodel', 'Custom Cabinetry'],
    license_number: 'CSLB-981120',
    license_classification: 'B',
    license_status: 'Active',
    license_issue_date: '2011-09-08',
    license_expiration_date: '2026-09-08',
    bond_status: 'Active',
    insurance_status: 'Active',
    address: '8721 Sunset Blvd',
    city: 'Los Angeles',
    county: 'Los Angeles',
    state: 'CA',
    zip_code: '90069',
    latitude: 34.0901,
    longitude: -118.3837,
    phone: '(310) 555-0177',
    website: 'https://coastlinekb.com',
    email: 'studio@coastlinekb.com',
    email_verified: true,
    contact_form_url: 'https://coastlinekb.com/contact',
    review_rating: 4.9,
    review_count: 241,
    source_count: 6,
    source_urls: ['Official License Source', 'Google Business', 'Yelp', 'Houzz', 'Company Website', 'Verified Email'],
    years_in_business: 14,
    estimated_company_size: 'Mid-Sized',
    estimated_business_maturity: 'Premium / Design-Forward',
    service_area: ['Los Angeles', 'Beverly Hills', 'Santa Monica', 'West Hollywood'],
    tags: ['premium', 'luxury', 'design-forward'],
    confidence_score: 98,
    last_verified_date: daysAgo(2),
    commercial_residential: 'Residential',
  },
  {
    contractor_id: 'c-004',
    company_name: 'Diaz Brothers Painting',
    contractor_type: 'Painter',
    specialties: ['Interior', 'Exterior', 'Cabinet Refinishing'],
    license_number: 'CSLB-554102',
    license_classification: 'C-33',
    license_status: 'Active',
    license_issue_date: '2018-01-15',
    license_expiration_date: '2026-01-15',
    bond_status: 'Active',
    insurance_status: 'Active',
    address: '1145 N Tustin Ave',
    city: 'Anaheim',
    county: 'Orange',
    state: 'CA',
    zip_code: '92807',
    latitude: 33.8366,
    longitude: -117.8311,
    phone: '(714) 555-0125',
    review_rating: 4.7,
    review_count: 38,
    source_count: 2,
    source_urls: ['Official License Source', 'Google Business'],
    years_in_business: 7,
    estimated_company_size: 'Small Crew',
    estimated_business_maturity: 'Low-Tech',
    service_area: ['Anaheim', 'Orange', 'Fullerton'],
    tags: ['no-website', 'small-crew', 'opportunity'],
    confidence_score: 71,
    last_verified_date: daysAgo(14),
    commercial_residential: 'Residential',
  },
  {
    contractor_id: 'c-005',
    company_name: 'Pacific Edge Electrical',
    contractor_type: 'Electrician',
    specialties: ['Residential Wiring', 'EV Chargers', 'Solar Tie-In'],
    license_number: 'CSLB-720889',
    license_classification: 'C-10',
    license_status: 'Active',
    license_issue_date: '2013-04-22',
    license_expiration_date: '2026-04-22',
    bond_status: 'Active',
    insurance_status: 'Active',
    address: '4421 Convoy St',
    city: 'San Diego',
    county: 'San Diego',
    state: 'CA',
    zip_code: '92111',
    latitude: 32.8128,
    longitude: -117.1542,
    phone: '(619) 555-0190',
    website: 'https://pacificedgeelec.com',
    email: 'service@pacificedgeelec.com',
    email_verified: true,
    review_rating: 4.8,
    review_count: 156,
    source_count: 5,
    source_urls: ['Official License Source', 'Google Business', 'Yelp', 'Company Website', 'Verified Email'],
    years_in_business: 12,
    estimated_company_size: 'Growing Local',
    estimated_business_maturity: 'Established',
    service_area: ['San Diego', 'La Jolla', 'Chula Vista'],
    tags: ['ev-charger', 'solar', 'digitally-mature'],
    confidence_score: 94,
    last_verified_date: daysAgo(4),
    commercial_residential: 'Residential',
  },
  {
    contractor_id: 'c-006',
    company_name: 'Goldstar Plumbing Co',
    contractor_type: 'Plumber',
    specialties: ['Repipe', 'Water Heaters', 'Drain Cleaning'],
    license_number: 'CSLB-441002',
    license_classification: 'C-36',
    license_status: 'Active',
    license_issue_date: '2010-11-03',
    license_expiration_date: '2025-11-03',
    bond_status: 'Active',
    insurance_status: 'Active',
    address: '987 Industrial Way',
    city: 'Oakland',
    county: 'Alameda',
    state: 'CA',
    zip_code: '94607',
    latitude: 37.8044,
    longitude: -122.2712,
    phone: '(510) 555-0166',
    website: 'https://goldstarplumb.com',
    review_rating: 4.5,
    review_count: 92,
    source_count: 4,
    source_urls: ['Official License Source', 'Google Business', 'Yelp', 'Company Website'],
    years_in_business: 15,
    estimated_company_size: 'Mid-Sized',
    estimated_business_maturity: 'Established',
    service_area: ['Oakland', 'Berkeley', 'Alameda', 'Emeryville'],
    tags: ['emergency', 'repipe', 'commercial'],
    confidence_score: 88,
    last_verified_date: daysAgo(9),
    commercial_residential: 'Both',
  },
  {
    contractor_id: 'c-007',
    company_name: 'Summit Roofing Solutions',
    contractor_type: 'Roofer',
    specialties: ['Composition Shingle', 'Tile', 'TPO'],
    license_number: 'CSLB-887234',
    license_classification: 'C-39',
    license_status: 'Active',
    license_issue_date: '2016-07-18',
    license_expiration_date: '2026-07-18',
    bond_status: 'Active',
    insurance_status: 'Active',
    address: '15233 Ventura Blvd',
    city: 'Sherman Oaks',
    county: 'Los Angeles',
    state: 'CA',
    zip_code: '91403',
    latitude: 34.1517,
    longitude: -118.4685,
    phone: '(818) 555-0133',
    website: 'https://summitroofingla.com',
    email: 'estimates@summitroofingla.com',
    email_verified: true,
    review_rating: 4.7,
    review_count: 124,
    source_count: 5,
    source_urls: ['Official License Source', 'Google Business', 'Yelp', 'Company Website', 'Verified Email'],
    years_in_business: 9,
    estimated_company_size: 'Growing Local',
    estimated_business_maturity: 'Established',
    service_area: ['Los Angeles', 'San Fernando Valley', 'Burbank'],
    tags: ['storm-response', 'residential', 'commercial'],
    confidence_score: 93,
    last_verified_date: daysAgo(5),
    commercial_residential: 'Both',
  },
  {
    contractor_id: 'c-008',
    company_name: 'NorCal HVAC Pros',
    contractor_type: 'HVAC',
    specialties: ['Heat Pumps', 'Ductless Mini-Split', 'Furnace Replace'],
    license_number: 'CSLB-330887',
    license_classification: 'C-20',
    license_status: 'Active',
    license_issue_date: '2012-02-09',
    license_expiration_date: '2025-02-09',
    bond_status: 'Active',
    insurance_status: 'Active',
    address: '2255 First St',
    city: 'Livermore',
    county: 'Alameda',
    state: 'CA',
    zip_code: '94550',
    latitude: 37.6819,
    longitude: -121.7685,
    phone: '(925) 555-0144',
    website: 'https://norcalhvacpros.com',
    email: 'office@norcalhvacpros.com',
    email_verified: false,
    review_rating: 4.6,
    review_count: 78,
    source_count: 4,
    source_urls: ['Official License Source', 'Google Business', 'Yelp', 'Company Website'],
    years_in_business: 13,
    estimated_company_size: 'Mid-Sized',
    estimated_business_maturity: 'Established',
    service_area: ['Livermore', 'Pleasanton', 'Dublin', 'Tri-Valley'],
    tags: ['heat-pump', 'rebate-program'],
    confidence_score: 84,
    last_verified_date: daysAgo(11),
    commercial_residential: 'Residential',
  },
  {
    contractor_id: 'c-009',
    company_name: 'Mendez Tile Works',
    contractor_type: 'Tile Installer',
    specialties: ['Bathroom Tile', 'Backsplash', 'Stone'],
    license_number: 'CSLB-220114',
    license_classification: 'C-54',
    license_status: 'Active',
    license_issue_date: '2019-05-14',
    license_expiration_date: '2025-05-14',
    bond_status: 'Active',
    insurance_status: 'None',
    address: '4412 Mission St',
    city: 'San Francisco',
    county: 'San Francisco',
    state: 'CA',
    zip_code: '94112',
    latitude: 37.7222,
    longitude: -122.4347,
    phone: '(415) 555-0102',
    review_rating: 4.4,
    review_count: 22,
    source_count: 2,
    source_urls: ['Official License Source', 'Google Business'],
    years_in_business: 6,
    estimated_company_size: 'Solo Operator',
    estimated_business_maturity: 'Low-Tech',
    service_area: ['San Francisco', 'Daly City'],
    tags: ['no-website', 'solo', 'opportunity'],
    confidence_score: 64,
    last_verified_date: daysAgo(21),
    commercial_residential: 'Residential',
  },
  {
    contractor_id: 'c-010',
    company_name: 'Heritage Cabinet & Millwork',
    contractor_type: 'Cabinet Installer',
    specialties: ['Custom Cabinets', 'Built-Ins', 'Pantry'],
    license_number: 'CSLB-770556',
    license_classification: 'C-6',
    license_status: 'Active',
    license_issue_date: '2007-10-30',
    license_expiration_date: '2026-10-30',
    bond_status: 'Active',
    insurance_status: 'Active',
    address: '1212 Park Ave',
    city: 'Emeryville',
    county: 'Alameda',
    state: 'CA',
    zip_code: '94608',
    latitude: 37.8313,
    longitude: -122.2852,
    phone: '(510) 555-0211',
    website: 'https://heritagecabinetca.com',
    email: 'studio@heritagecabinetca.com',
    email_verified: true,
    contact_form_url: 'https://heritagecabinetca.com/inquire',
    review_rating: 4.9,
    review_count: 89,
    source_count: 6,
    source_urls: ['Official License Source', 'Google Business', 'Yelp', 'Houzz', 'Company Website', 'Verified Email'],
    years_in_business: 18,
    estimated_company_size: 'Mid-Sized',
    estimated_business_maturity: 'Premium / Design-Forward',
    service_area: ['Emeryville', 'Berkeley', 'Oakland', 'San Francisco'],
    tags: ['premium', 'custom', 'design-forward'],
    confidence_score: 97,
    last_verified_date: daysAgo(1),
    commercial_residential: 'Residential',
  },
  {
    contractor_id: 'c-011',
    company_name: 'Cobalt Construction Group',
    contractor_type: 'General Contractor',
    specialties: ['Commercial Build-Out', 'TI', 'Restaurant'],
    license_number: 'CSLB-118823',
    license_classification: 'B',
    license_status: 'Active',
    license_issue_date: '2005-08-12',
    license_expiration_date: '2026-08-12',
    bond_status: 'Active',
    insurance_status: 'Active',
    address: '2050 Powell St',
    city: 'Emeryville',
    county: 'Alameda',
    state: 'CA',
    zip_code: '94608',
    latitude: 37.8344,
    longitude: -122.2904,
    phone: '(510) 555-0299',
    website: 'https://cobaltcg.com',
    email: 'projects@cobaltcg.com',
    email_verified: true,
    review_rating: 4.8,
    review_count: 41,
    source_count: 5,
    source_urls: ['Official License Source', 'Google Business', 'Houzz', 'Company Website', 'Verified Email'],
    years_in_business: 20,
    estimated_company_size: 'Multi-Location',
    estimated_business_maturity: 'Established',
    service_area: ['Bay Area', 'Sacramento', 'Los Angeles'],
    tags: ['commercial', 'multi-location', 'enterprise'],
    confidence_score: 95,
    last_verified_date: daysAgo(3),
    commercial_residential: 'Commercial',
  },
  {
    contractor_id: 'c-012',
    company_name: 'Garcia Handyman Services',
    contractor_type: 'Handyman',
    specialties: ['Repairs', 'Small Jobs', 'Fence Repair'],
    license_number: 'UNLICENSED',
    license_classification: 'N/A',
    license_status: 'Inactive',
    license_issue_date: '',
    license_expiration_date: '',
    bond_status: 'None',
    insurance_status: 'None',
    address: '',
    city: 'Fresno',
    county: 'Fresno',
    state: 'CA',
    zip_code: '93722',
    latitude: 36.7372,
    longitude: -119.7871,
    phone: '(559) 555-0114',
    review_rating: 4.3,
    review_count: 12,
    source_count: 1,
    source_urls: ['Google Business'],
    years_in_business: 3,
    estimated_company_size: 'Solo Operator',
    estimated_business_maturity: 'Low-Tech',
    service_area: ['Fresno', 'Clovis'],
    tags: ['unlicensed', 'small-jobs'],
    confidence_score: 42,
    last_verified_date: daysAgo(35),
    commercial_residential: 'Residential',
  },
  {
    contractor_id: 'c-013',
    company_name: 'Sierra Roofing & Solar',
    contractor_type: 'Roofer',
    specialties: ['Solar Roof', 'Composition', 'Gutters'],
    license_number: 'CSLB-665899',
    license_classification: 'C-39',
    license_status: 'Active',
    license_issue_date: '2015-12-01',
    license_expiration_date: '2025-12-01',
    bond_status: 'Active',
    insurance_status: 'Active',
    address: '3120 N Blackstone Ave',
    city: 'Fresno',
    county: 'Fresno',
    state: 'CA',
    zip_code: '93703',
    latitude: 36.8156,
    longitude: -119.7902,
    phone: '(559) 555-0188',
    website: 'https://sierraroofingsolar.com',
    email: 'info@sierraroofingsolar.com',
    email_verified: true,
    review_rating: 4.6,
    review_count: 53,
    source_count: 4,
    source_urls: ['Official License Source', 'Google Business', 'Company Website', 'Verified Email'],
    years_in_business: 10,
    estimated_company_size: 'Growing Local',
    estimated_business_maturity: 'Established',
    service_area: ['Fresno', 'Clovis', 'Madera'],
    tags: ['solar', 'central-valley'],
    confidence_score: 90,
    last_verified_date: daysAgo(6),
    commercial_residential: 'Residential',
  },
  {
    contractor_id: 'c-014',
    company_name: 'Studio Verde Landscape',
    contractor_type: 'Landscaping',
    specialties: ['Drought-Tolerant', 'Outdoor Living', 'Hardscape'],
    license_number: 'CSLB-554903',
    license_classification: 'C-27',
    license_status: 'Active',
    license_issue_date: '2017-03-22',
    license_expiration_date: '2026-03-22',
    bond_status: 'Active',
    insurance_status: 'Active',
    address: '780 Bay Rd',
    city: 'Menlo Park',
    county: 'San Mateo',
    state: 'CA',
    zip_code: '94025',
    latitude: 37.4633,
    longitude: -122.1723,
    phone: '(650) 555-0177',
    website: 'https://studioverdela.com',
    email: 'design@studioverdela.com',
    email_verified: true,
    review_rating: 4.9,
    review_count: 76,
    source_count: 5,
    source_urls: ['Official License Source', 'Google Business', 'Houzz', 'Company Website', 'Verified Email'],
    years_in_business: 8,
    estimated_company_size: 'Growing Local',
    estimated_business_maturity: 'Premium / Design-Forward',
    service_area: ['Menlo Park', 'Palo Alto', 'Atherton', 'Woodside'],
    tags: ['premium', 'design-forward', 'sustainable'],
    confidence_score: 96,
    last_verified_date: daysAgo(2),
    commercial_residential: 'Residential',
  },
  {
    contractor_id: 'c-015',
    company_name: 'BluePeak Electrical',
    contractor_type: 'Electrician',
    specialties: ['Panel Upgrades', 'Service Calls'],
    license_number: 'CSLB-998112',
    license_classification: 'C-10',
    license_status: 'Expired',
    license_issue_date: '2009-09-09',
    license_expiration_date: '2024-09-09',
    bond_status: 'Expired',
    insurance_status: 'Expired',
    address: '12 Industrial Blvd',
    city: 'Stockton',
    county: 'San Joaquin',
    state: 'CA',
    zip_code: '95206',
    latitude: 37.9577,
    longitude: -121.2908,
    phone: '(209) 555-0144',
    review_rating: 3.9,
    review_count: 18,
    source_count: 2,
    source_urls: ['Official License Source', 'Google Business'],
    years_in_business: 16,
    estimated_company_size: 'Small Crew',
    estimated_business_maturity: 'Low-Tech',
    service_area: ['Stockton', 'Lodi'],
    tags: ['expired-license', 'stale'],
    confidence_score: 51,
    last_verified_date: daysAgo(45),
    commercial_residential: 'Residential',
  },
];

export const seedSegments: SavedSegment[] = [
  {
    id: 's-001',
    name: 'Licensed Flooring Installers in San Jose',
    notes: 'Active CSLB C-15 + verified email + website',
    filters: {
      contractorTypes: ['Flooring Installer'],
      cities: ['San Jose'],
      licenseStatus: ['Active'],
      hasWebsite: true,
      hasVerifiedEmail: true,
    },
    contractor_ids: ['c-001'],
    created_at: daysAgo(8),
  },
  {
    id: 's-002',
    name: 'Small General Contractors in Santa Clara County',
    filters: {
      contractorTypes: ['General Contractor'],
      counties: ['Santa Clara'],
      companySizes: ['Solo Operator', 'Small Crew', 'Growing Local'],
      licenseStatus: ['Active'],
    },
    contractor_ids: [],
    created_at: daysAgo(12),
  },
  {
    id: 's-003',
    name: 'Premium Kitchen Remodelers in LA',
    filters: {
      contractorTypes: ['Kitchen / Bath Remodeler'],
      cities: ['Los Angeles'],
      maturity: ['Premium / Design-Forward'],
    },
    contractor_ids: ['c-003'],
    created_at: daysAgo(4),
  },
  {
    id: 's-004',
    name: 'High-confidence Verified Email — NorCal',
    filters: {
      states: ['CA'],
      hasVerifiedEmail: true,
      minConfidence: 90,
    },
    contractor_ids: ['c-001', 'c-005', 'c-010', 'c-014'],
    created_at: daysAgo(2),
  },
];
