import type { VibinCard, Deck, VibinState } from './types';

const u = (id: string, q: string) =>
  `https://images.unsplash.com/${id}?auto=format&fit=crop&w=900&q=80`;

export const seedCards: VibinCard[] = [
  {
    id: 'c-ggb',
    title: 'Golden Gate Bridge',
    image: u('photo-1501594907352-04cda38ebc29', 'golden gate'),
    category: 'place',
    description: 'The iconic orange spans, framed by fog and bay.',
    note: 'Sunset hits different from the Marin side. Walk from Battery Spencer.',
    tags: ['scenic', 'iconic', 'photo-spot'],
    durationMin: 60,
    bestTime: 'evening',
    cost: '$',
    locationName: 'Golden Gate Bridge, SF',
    lat: 37.8199, lng: -122.4783,
    tip: 'Park at Battery Spencer — free, fewer crowds.',
    createdAt: Date.now() - 1000000,
    authorName: 'Maya K.',
  },
  {
    id: 'c-tartine',
    title: 'Tartine Bakery',
    image: u('photo-1509440159596-0249088772ff', 'pastry'),
    category: 'food',
    description: 'Croissants worth the line. Morning bun is non-negotiable.',
    note: 'Get there before 9am or accept your fate.',
    tags: ['foodie', 'breakfast', 'iconic'],
    durationMin: 45,
    bestTime: 'morning',
    cost: '$$',
    locationName: 'Mission, SF',
    lat: 37.7614, lng: -122.4241,
    tip: 'Cash for tips. Outdoor benches across the street.',
    createdAt: Date.now() - 900000,
    authorName: 'Maya K.',
  },
  {
    id: 'c-half-moon',
    title: 'Half Moon Bay',
    image: u('photo-1507525428034-b723cf961d3e', 'beach'),
    category: 'place',
    description: 'Wide quiet beach, tidepools, and a bluff trail.',
    tags: ['scenic', 'coastal', 'meditative'],
    durationMin: 120,
    bestTime: 'afternoon',
    cost: '$',
    locationName: 'Half Moon Bay, CA',
    lat: 37.4636, lng: -122.4286,
    tip: 'Stop at Sam\'s Chowder House for lobster roll.',
    createdAt: Date.now() - 800000,
    authorName: 'Maya K.',
  },
  {
    id: 'c-lands-end',
    title: 'Lands End Trail',
    image: u('photo-1469854523086-cc02fe5d8800', 'cliff trail'),
    category: 'experience',
    description: 'Cliffside walk with shipwreck views and cypress tunnels.',
    tags: ['scenic', 'active', 'meditative'],
    durationMin: 90,
    bestTime: 'morning',
    cost: '$',
    locationName: 'Outer Richmond, SF',
    lat: 37.7811, lng: -122.5106,
    createdAt: Date.now() - 700000,
    authorName: 'Maya K.',
  },
  {
    id: 'c-ferry',
    title: 'Ferry Building Marketplace',
    image: u('photo-1555396273-367ea4eb4db5', 'market'),
    category: 'food',
    description: 'Best food hall in the city. Hog Island oysters, Acme bread.',
    tags: ['foodie', 'iconic', 'lunch'],
    durationMin: 75,
    bestTime: 'afternoon',
    cost: '$$',
    locationName: 'Embarcadero, SF',
    lat: 37.7956, lng: -122.3933,
    tip: 'Saturday farmers market 8am–2pm is the move.',
    createdAt: Date.now() - 600000,
    authorName: 'Maya K.',
  },
  {
    id: 'c-mission-burrito',
    title: 'La Taqueria',
    image: u('photo-1565299585323-38d6b0865b47', 'tacos'),
    category: 'food',
    description: 'Mission-style burrito, no rice, dorado on the outside.',
    tags: ['foodie', 'lunch', 'cheap-eats'],
    durationMin: 40,
    bestTime: 'afternoon',
    cost: '$',
    locationName: 'Mission, SF',
    lat: 37.7508, lng: -122.4180,
    createdAt: Date.now() - 500000,
    authorName: 'Diego R.',
  },
  {
    id: 'c-twin-peaks',
    title: 'Twin Peaks',
    image: u('photo-1518391846015-55a9cc003b25', 'cityview'),
    category: 'place',
    description: '360° view of the entire bay — bring a jacket, it\'s windy.',
    tags: ['scenic', 'photo-spot', 'sunset'],
    durationMin: 45,
    bestTime: 'evening',
    cost: '$',
    locationName: 'Twin Peaks, SF',
    lat: 37.7544, lng: -122.4477,
    createdAt: Date.now() - 400000,
    authorName: 'Maya K.',
  },
  {
    id: 'c-sutro',
    title: 'Sutro Baths Ruins',
    image: u('photo-1502602898657-3e91760cbb34', 'ocean'),
    category: 'experience',
    description: 'Crumbling Victorian baths at the edge of the Pacific.',
    tags: ['scenic', 'historic', 'meditative'],
    durationMin: 60,
    bestTime: 'evening',
    cost: '$',
    locationName: 'Outer Richmond, SF',
    lat: 37.7800, lng: -122.5135,
    createdAt: Date.now() - 300000,
  },
];

export const seedDecks: Deck[] = [
  {
    id: 'd-1day-sf',
    title: '1 Day San Francisco',
    description: 'The greatest hits, paced so you actually enjoy it.',
    duration: 'full-day',
    coverImage: seedCards[0].image,
    cardIds: ['c-tartine', 'c-ggb', 'c-lands-end', 'c-ferry', 'c-twin-peaks'],
    optionalCardIds: ['c-sutro'],
    authorName: 'Maya K.',
    createdAt: Date.now() - 200000,
  },
  {
    id: 'd-coastal',
    title: 'Half-Day Coastal Escape',
    description: 'Salt air, cliff walks, and one perfect lunch.',
    duration: 'half-day',
    coverImage: seedCards[2].image,
    cardIds: ['c-lands-end', 'c-sutro', 'c-half-moon'],
    authorName: 'Maya K.',
    createdAt: Date.now() - 150000,
  },
  {
    id: 'd-foodie',
    title: 'Foodie Weekend',
    description: 'Every meal earns its calories.',
    duration: 'multi-day',
    coverImage: seedCards[1].image,
    cardIds: ['c-tartine', 'c-mission-burrito', 'c-ferry'],
    authorName: 'Diego R.',
    createdAt: Date.now() - 100000,
  },
];

export const seedState: VibinState = {
  cards: seedCards,
  decks: seedDecks,
  trips: [],
  profile: {
    name: 'You',
    handle: '@curator',
    bio: 'Collecting places that made me pause.',
    avatar: u('photo-1494790108377-be9c29b29330', 'avatar'),
  },
};
